# https://docs.quarkiverse.io/quarkus-openapi-generator/dev/client.html
quarkus.openapi-generator.codegen.enable-security-generation=false
# https://docs.mapbox.com/api/navigation/directions/
quarkus.openapi-generator.codegen.spec.directions_yaml.base-package=io.quarkiverse.mapbox.directions
quarkus.openapi-generator.codegen.spec.directions_yaml.config-key=directions
quarkus.openapi-generator.codegen.spec.directions_yaml.type-mappings.File=byte[]
# https://docs.mapbox.com/api/search/geocoding/
quarkus.openapi-generator.codegen.spec.geocoding_yaml.base-package=io.quarkiverse.mapbox.geocoding
quarkus.openapi-generator.codegen.spec.geocoding_yaml.config-key=geocoding
quarkus.openapi-generator.codegen.spec.geocoding_yaml.type-mappings.File=byte[]